# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-10 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ahanu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('here', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('ciro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.ibyiciro')),
                ('hanu', models.ManyToManyField(to='gallery.Ahanu')),
            ],
        ),
    ]
