# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-11 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_ahanu_pics'),
    ]

    operations = [
        migrations.AddField(
            model_name='pics',
            name='pic',
            field=models.ImageField(null=True, upload_to='pictures/'),
        ),
    ]
